Repository MinecraftForge/ForgeFlower, pull requests merged in 2022-05, with the labels that each got.

#115 Simplify threaded output handling/stabilize output
  FernFlower-Patches/0005-Fix-output-discrepancies-to-produce-stable-output.patch
  FernFlower-Patches/0019-Add-cfg-argument-Used-to-specify-a-text-file-with-ad.patch
  FernFlower-Patches/0020-Add-support-for-destination-to-be-a-zip-file-if-ther.patch
  FernFlower-Patches/0034-Add-only-argument-It-will-filter-what-classes-are-de.patch
  FernFlower-Patches/0038-Make-decomp-threaded.patch
  FernFlower-Patches/0039-Expose-line-mapping-information-in-archive-mode.patch
  gradle.properties
Labels: type: bug

#116 Cache file data to reduce lock contention
  FernFlower-Patches/0038-Make-decomp-threaded.patch
  FernFlower-Patches/0047-Cache-zip-file-instances-and-source-class-data.patch
Labels: type: enhancement, status: need update

#117 Respect DUMP_CODE_LINES option
  FernFlower-Patches/0039-Expose-line-mapping-information-in-archive-mode.patch
  FernFlower-Patches/0047-Cache-zip-file-instances-and-source-class-data.patch
Labels: status: need update
